name: CDK Deploy to AWS - Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install NPM dependencies
        run: npm install

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Configure AWS Credentials for Prod
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_PROD }}

      - name: Build CDK app
        working-directory: ./cdk
        run: |
          go mod download
          go build

      - name: CDK Deploy to Prod
        env:
          ENVIRONMENT: prod
        run: npm run deploy
